// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
export interface BannerItem {
  title?: string;
  subTitle?: string;
  image?: StoryblokAsset;
  component: "bannerItem";
  _uid: string;
  [k: string]: unknown;
}

export interface BannerList {
  bannerItem?: BannerItem[];
  component: "bannerList";
  _uid: string;
  [k: string]: unknown;
}

export interface Depth1 {
  title?: string;
  subTitle?: string;
  body?: (BannerList | LendingList)[];
  component: "depth1";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (
    | BannerItem
    | BannerList
    | Depth1
    | Feature
    | Grid
    | Header
    | LendingItem
    | LendingList
    | Login
    | NavLogo
    | NavMenu
    | Page
    | Product
    | ProductCard
    | ProductList
    | Signup
    | Teaser
  )[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  body?: (
    | BannerItem
    | BannerList
    | Depth1
    | Feature
    | Grid
    | Header
    | LendingItem
    | LendingList
    | Login
    | NavLogo
    | NavMenu
    | Page
    | Product
    | ProductCard
    | ProductList
    | Signup
    | Teaser
  )[];
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface LendingItem {
  title?: string;
  link?: string;
  img?: StoryblokAsset;
  component: "lendingItem";
  _uid: string;
  [k: string]: unknown;
}

export interface LendingList {
  sectionTitle?: string;
  lendingItem?: LendingItem[];
  component: "lendingList";
  _uid: string;
  [k: string]: unknown;
}

export interface Login {
  id: string;
  pwd: string;
  submit?: string;
  title?: string;
  description?: string;
  component: "login";
  _uid: string;
  [k: string]: unknown;
}

export interface NavLogo {
  image?: StoryblokAsset;
  component: "nav-logo";
  _uid: string;
  [k: string]: unknown;
}

export interface NavMenu {
  links?: (
    | BannerItem
    | BannerList
    | Depth1
    | Feature
    | Grid
    | Header
    | LendingItem
    | LendingList
    | Login
    | NavLogo
    | NavMenu
    | Page
    | Product
    | ProductCard
    | ProductList
    | Signup
    | Teaser
  )[];
  component: "nav-menu";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | BannerItem
    | BannerList
    | Depth1
    | Feature
    | Grid
    | Header
    | LendingItem
    | LendingList
    | Login
    | NavLogo
    | NavMenu
    | Page
    | Product
    | ProductCard
    | ProductList
    | Signup
    | Teaser
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Product {
  body?: ProductList[];
  component: "product";
  _uid: string;
  [k: string]: unknown;
}

export interface ProductCard {
  name?: string;
  price?: string;
  image?: StoryblokAsset;
  sku?: string;
  badge?: string;
  component: "product-card";
  _uid: string;
  [k: string]: unknown;
}

export interface ProductList {
  title?: string;
  component: "product-list";
  _uid: string;
  [k: string]: unknown;
}

export interface Signup {
  id: string;
  pwd: string;
  submit?: string;
  title?: string;
  description?: string;
  component: "signup";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Header | Page | Product;
